version = 1

[schema]

[[schema.tables]]
id = 0
name = "svc_api_keys"
primary_key = { columns = [{ table = 0, index = 0 }], index = { table = 0, index = 0 } }

[[schema.tables.columns]]
id = { table = 0, index = 0 }
name = "id"
ty = "Bytes"
storage_ty = "Blob"

[[schema.tables.columns]]
id = { table = 0, index = 1 }
name = "tenant_id"
ty = "Bytes"
storage_ty = "Blob"

[[schema.tables.columns]]
id = { table = 0, index = 2 }
name = "token"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 0, index = 0 }
name = "index_svc_api_keys_by_id"
on = 0
columns = [{ column = { table = 0, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 0, index = 1 }
name = "index_svc_api_keys_by_tenant_id"
on = 0
columns = [{ column = { table = 0, index = 1 }, op = "Eq", scope = "Partition" }]

[[schema.tables.indices]]
id = { table = 0, index = 2 }
name = "index_svc_api_keys_by_token"
on = 0
columns = [{ column = { table = 0, index = 2 }, op = "Eq", scope = "Partition" }]
unique = true

[[schema.tables]]
id = 1
name = "svc_tenants"
primary_key = { columns = [{ table = 1, index = 0 }], index = { table = 1, index = 0 } }

[[schema.tables.columns]]
id = { table = 1, index = 0 }
name = "id"
ty = "Bytes"
storage_ty = "Blob"

[[schema.tables.columns]]
id = { table = 1, index = 1 }
name = "slug"
ty = "String"
storage_ty = "Text"

[[schema.tables.columns]]
id = { table = 1, index = 2 }
name = "name"
ty = "String"
storage_ty = "Text"

[[schema.tables.indices]]
id = { table = 1, index = 0 }
name = "index_svc_tenants_by_id"
on = 1
columns = [{ column = { table = 1, index = 0 }, op = "Eq", scope = "Partition" }]
unique = true
primary_key = true

[[schema.tables.indices]]
id = { table = 1, index = 1 }
name = "index_svc_tenants_by_slug"
on = 1
columns = [{ column = { table = 1, index = 1 }, op = "Eq", scope = "Partition" }]
unique = true
