//! Rustdoc strings for all public items generated by `#[derive(Model)]` and
//! `#[derive(Embed)]`.
//!
//! Keeping the doc text in a single module makes it easy to review and edit
//! without cluttering the token-generation code in the sibling expand files.

// === Model impl methods =====================================================

pub(super) fn model_create(model: &str, create: &str) -> String {
    format!(
        "Return a builder for creating a new [`{model}`] record.\n\
         \n\
         Set field values on the returned builder, then call\n\
         [`.exec()`]({create}::exec) to insert the record.\n\
         \n\
         See the [Toasty guide](https://docs.rs/toasty/latest/toasty/#derive-macros) \
         for more on create builders."
    )
}

pub(super) fn model_create_many(model: &str) -> String {
    format!("Return a builder for inserting multiple [`{model}`] records in a single operation.")
}

pub(super) fn model_update(model: &str, update: &str) -> String {
    format!(
        "Return a builder for updating this [`{model}`] record.\n\
         \n\
         Set field values on the returned builder, then call\n\
         [`.exec()`]({update}::exec) to apply the changes.\n\
         After execution, `self` is reloaded with the updated values."
    )
}

pub(super) fn model_all(model: &str, query: &str) -> String {
    format!(
        "Return a query that selects all [`{model}`] records.\n\
         \n\
         Chain [`.filter()`]({query}::filter), [`.order_by()`]({query}::order_by),\n\
         [`.limit()`]({query}::limit), or other methods on the returned\n\
         query to narrow results before calling [`.exec()`]({query}::exec)."
    )
}

pub(super) fn model_filter(model: &str) -> String {
    format!(
        "Return a query for [`{model}`] records matching the given filter expression.\n\
         \n\
         Build filter expressions using [`{model}::fields()`]."
    )
}

pub(super) fn model_delete(model: &str) -> String {
    format!(
        "Delete this [`{model}`] record from the database.\n\
         \n\
         Call [`.exec()`](toasty::stmt::Delete::exec) on the returned\n\
         statement to execute the deletion."
    )
}

// === Fields ==================================================================

pub(super) fn model_fields(model: &str, fields_struct: &str, example_field: &str) -> String {
    format!(
        "Return typed field paths for building filter expressions.\n\
         \n\
         Each accessor on the returned [`{fields_struct}`] corresponds to a\n\
         field on [`{model}`] and can be used to build comparisons,\n\
         e.g. `{model}::fields().{example_field}.eq(value)`."
    )
}

pub(super) fn field_struct(model: &str) -> String {
    format!(
        "Typed field paths for [`{model}`].\n\
         \n\
         Returned by [`{model}::fields()`]. Use the accessor methods\n\
         to build filter expressions and navigate to related models.\n\
         \n\
         See the [Toasty guide](https://docs.rs/toasty/latest/toasty/) for\n\
         examples of building queries with field paths."
    )
}

pub(super) fn field_struct_eq(model: &str) -> String {
    format!(
        "Return a filter expression that matches [`{model}`] records\n\
         equal to `rhs` (compared by primary key)."
    )
}

pub(super) fn field_struct_in_query(model: &str) -> String {
    format!(
        "Return a filter expression that matches [`{model}`] records\n\
         whose primary key appears in the result set of `rhs`."
    )
}

pub(super) fn field_struct_create(model: &str) -> String {
    format!("Return a new create builder for [`{model}`].")
}

pub(super) fn field_list_struct(model: &str) -> String {
    format!(
        "Typed field paths for a list of [`{model}`] records.\n\
         \n\
         Used when navigating from a has-many association to build\n\
         sub-filters and access nested fields."
    )
}

pub(super) fn field_list_any(model: &str) -> String {
    format!(
        "Return a filter expression that is `true` when **any** associated\n\
         [`{model}`] record satisfies `filter`.\n\
         \n\
         Use this to filter a parent model by a condition on its children."
    )
}

pub(super) fn field_accessor(field: &str) -> String {
    format!("Access the `{field}` field path for building filter expressions.")
}

pub(super) fn relation_field_accessor(field: &str) -> String {
    format!("Access the `{field}` relation path for building filter expressions.")
}

pub(super) fn has_many_field_accessor(field: &str) -> String {
    format!("Access the `{field}` has-many relation path.")
}

pub(super) fn list_field_accessor(field: &str) -> String {
    format!("Access the `{field}` field path within this list context.")
}

pub(super) fn list_relation_accessor(field: &str) -> String {
    format!("Access the `{field}` relation path within this list context.")
}

// === Query ===================================================================

pub(super) fn query_struct(model: &str) -> String {
    format!(
        "A query builder for [`{model}`] records.\n\
         \n\
         Returned by [`{model}::all()`] and [`{model}::filter()`].\n\
         Chain methods to narrow results, then execute with [`.exec()`](Self::exec)\n\
         or [`.get()`](Self::get)."
    )
}

pub(super) fn query_from_stmt(query: &str) -> String {
    format!("Create a [`{query}`] from a raw query statement.")
}

pub(super) fn query_exec(model: &str) -> String {
    format!("Execute the query and return all matching [`{model}`] records.")
}

pub(super) fn query_first(model: &str) -> String {
    format!("Expect at most one result. Returns `None` if no [`{model}`] matches.")
}

pub(super) fn query_one(model: &str) -> String {
    format!("Expect exactly one result. Returns an error if no [`{model}`] matches.")
}

pub(super) fn query_get(model: &str) -> String {
    format!(
        "Execute the query and return exactly one [`{model}`].\n\
         \n\
         Shorthand for `.one().exec(executor)`."
    )
}

pub(super) fn query_update(model: &str) -> String {
    format!(
        "Convert this query into an update builder.\n\
         \n\
         All [`{model}`] records matching the current filters will be updated."
    )
}

pub(super) fn query_count(model: &str) -> String {
    format!("Count the [`{model}`] records matching the current filters.")
}

pub(super) fn query_delete(model: &str) -> String {
    format!("Delete all [`{model}`] records matching the current filters.")
}

pub(super) fn query_paginate(model: &str) -> String {
    format!("Paginate results, returning `per_page` [`{model}`] records at a time.")
}

pub(super) const QUERY_FILTER: &str =
    "Add a filter expression to this query, narrowing the result set.";

pub(super) const QUERY_ORDER_BY: &str = "Set the sort order for the query results.";

pub(super) const QUERY_LIMIT: &str = "Limit the number of records returned.";

pub(super) const QUERY_OFFSET: &str = "Skip the first `n` matching records.";

pub(super) fn query_include(model: &str, example_relation: &str) -> String {
    format!(
        "Eagerly load an association so it is available without a separate query.\n\
         \n\
         Pass a field path obtained from [`{model}::fields()`], such as\n\
         `{model}::fields().{example_relation}`, to specify which association to load."
    )
}

pub(super) fn query_relation_navigate(model: &str, field: &str) -> String {
    format!("Navigate from the selected [`{model}`] records to their associated `{field}` records.")
}

pub(super) fn query_relation_navigate_one(model: &str, field: &str) -> String {
    format!("Navigate from the selected [`{model}`] records to their associated `{field}` record.")
}

// === Create ==================================================================

pub(super) fn create_struct(model: &str) -> String {
    format!(
        "A create builder for inserting a new [`{model}`] record.\n\
         \n\
         Returned by [`{model}::create()`]. Set field values using the\n\
         builder methods, then call [`.exec()`](Self::exec) to insert the record\n\
         and get back the created [`{model}`]."
    )
}

pub(super) fn create_exec(model: &str) -> String {
    format!("Execute the insert and return the newly created [`{model}`].")
}

pub(super) fn create_field_setter(model: &str, field: &str) -> String {
    format!("Set the `{field}` field for the new [`{model}`] record.")
}

pub(super) fn create_has_many_singular(model: &str, field: &str) -> String {
    format!("Add a single associated `{field}` record to the new [`{model}`].")
}

pub(super) fn create_has_many_plural(model: &str, field: &str) -> String {
    format!("Add multiple associated `{field}` records to the new [`{model}`].")
}

// === Update ==================================================================

pub(super) fn update_struct(model: &str, query: &str) -> String {
    format!(
        "An update builder for [`{model}`] records.\n\
         \n\
         Returned by [`{model}::update()`] (instance update) or\n\
         [`{query}::update()`] (query-based batch update). Set\n\
         field values using the builder methods, then call\n\
         [`.exec()`](Self::exec) to apply the changes."
    )
}

pub(super) fn update_exec(model: &str) -> String {
    format!(
        "Execute the update statement.\n\
         \n\
         For instance updates ([`{model}::update()`]), the model is\n\
         reloaded with the new values after the update completes."
    )
}

pub(super) fn update_embedded_struct(model: &str) -> String {
    format!(
        "An update builder for the embedded [`{model}`] type.\n\
         \n\
         Set individual fields on the embedded struct without replacing the\n\
         entire value."
    )
}

pub(super) fn update_field_consuming(field: &str) -> String {
    format!("Set the `{field}` field (consuming builder).")
}

pub(super) fn update_field_by_ref(field: &str) -> String {
    format!("Set the `{field}` field (by mutable reference).")
}

pub(super) fn update_field_with(field: &str) -> String {
    format!(
        "Update the nested `{field}` embedded field.\n\
         \n\
         The closure receives an update builder scoped to the embedded\n\
         type, allowing individual sub-fields to be set."
    )
}

// === Filters =================================================================

pub(super) fn filter_get(model: &str, fields: &str) -> String {
    format!(
        "Find and return a single [`{model}`] by `{fields}`.\n\
         \n\
         Returns an error if no matching record exists."
    )
}

pub(super) fn filter_update(model: &str, fields: &str) -> String {
    format!("Return an update builder for [`{model}`] records matching `{fields}`.")
}

pub(super) fn filter_delete(model: &str, fields: &str) -> String {
    format!("Delete [`{model}`] records matching `{fields}`.")
}

pub(super) fn filter_by(model: &str, fields: &str) -> String {
    format!("Return a query for [`{model}`] records matching `{fields}`.")
}

pub(super) fn filter_query_by(model: &str, fields: &str) -> String {
    format!("Add a filter for `{fields}` to this [`{model}`] query.")
}

// === Relation structs ========================================================

pub(super) fn relation_many(model: &str, example: &str) -> String {
    format!(
        "A has-many association handle for [`{model}`].\n\
         \n\
         Obtained by calling a has-many accessor on a model instance\n\
         (e.g. `user.{example}()`). Provides methods to query, create,\n\
         insert, and remove associated records."
    )
}

pub(super) fn relation_one(model: &str) -> String {
    format!(
        "A has-one or belongs-to association handle for [`{model}`].\n\
         \n\
         Obtained by calling a has-one or belongs-to accessor on a model\n\
         instance. Provides methods to load or create the associated record."
    )
}

pub(super) fn relation_option_one(model: &str) -> String {
    format!(
        "An optional association handle for [`{model}`].\n\
         \n\
         Like [`One`], but [`.exec()`](Self::exec) returns `Option<{model}>`\n\
         instead of returning an error when no associated record exists."
    )
}

pub(super) fn many_exec(model: &str) -> String {
    format!("Load all associated [`{model}`] records.")
}

pub(super) fn many_query(model: &str) -> String {
    format!(
        "Return a query over the associated [`{model}`] records\n\
         with an additional filter."
    )
}

pub(super) fn many_create(model: &str) -> String {
    format!("Create a new [`{model}`] record scoped to this association.")
}

pub(super) fn many_insert(model: &str) -> String {
    format!("Add an existing [`{model}`] to this association.")
}

pub(super) fn many_remove(model: &str) -> String {
    format!("Remove a [`{model}`] from this association.")
}

pub(super) fn one_create(model: &str) -> String {
    format!("Create a new associated [`{model}`] record.")
}

pub(super) fn one_exec(model: &str) -> String {
    format!(
        "Load the associated [`{model}`] record.\n\
         \n\
         Returns an error if the associated record does not exist."
    )
}

pub(super) fn option_one_exec(model: &str) -> String {
    format!("Load the associated [`{model}`] record, if it exists.")
}

// === Model-level relation accessors ==========================================

pub(super) fn model_belongs_to(field: &str) -> String {
    format!(
        "Access the `{field}` belongs-to association for this record.\n\
         \n\
         Returns a handle for loading or creating the associated record."
    )
}

pub(super) fn model_has_many(field: &str) -> String {
    format!(
        "Access the `{field}` has-many association for this record.\n\
         \n\
         Returns a handle for querying, creating, inserting, and\n\
         removing associated records."
    )
}

pub(super) fn model_has_one(field: &str) -> String {
    format!(
        "Access the `{field}` has-one association for this record.\n\
         \n\
         Returns a handle for loading or creating the associated record."
    )
}

// === Embedded enum ===========================================================

pub(super) fn enum_field_struct(model: &str) -> String {
    format!(
        "Typed field paths for the [`{model}`] enum.\n\
         \n\
         Provides `is_<variant>()` methods for filtering by variant and\n\
         accessor methods for navigating into data-carrying variant fields."
    )
}

pub(super) fn enum_is_variant(model: &str, variant: &str) -> String {
    format!(
        "Return a filter expression that is `true` when this\n\
         [`{model}`] is the `{variant}` variant."
    )
}

pub(super) fn enum_variant_accessor(variant: &str, handle: &str) -> String {
    format!(
        "Access the `{variant}` variant's field paths.\n\
         \n\
         Use [`.matches()`]({handle}::matches) on the returned handle to\n\
         build filters that match the variant and its field values."
    )
}

pub(super) fn enum_variant_handle(model: &str, variant: &str) -> String {
    format!(
        "A handle to the `{variant}` variant of [`{model}`].\n\
         \n\
         Provides a [`matches()`](Self::matches) method for building\n\
         filters that check both the variant discriminant and field values."
    )
}

pub(super) fn enum_variant_matches(variant: &str, fields_struct: &str) -> String {
    format!(
        "Build a filter that matches the `{variant}` variant with\n\
         additional field-level conditions.\n\
         \n\
         The closure receives a [`{fields_struct}`] for building\n\
         comparisons on the variant's fields. The returned expression\n\
         combines the variant check with the field conditions."
    )
}

pub(super) fn enum_variant_field_struct(model: &str, variant: &str) -> String {
    format!("Typed field paths for the `{variant}` variant of [`{model}`].")
}

pub(super) fn enum_eq(model: &str) -> String {
    format!("Return a filter expression that is `true` when this [`{model}`] equals `rhs`.")
}

pub(super) fn enum_ne(model: &str) -> String {
    format!("Return a filter expression that is `true` when this [`{model}`] does not equal `rhs`.")
}

pub(super) fn enum_in_list(model: &str) -> String {
    format!(
        "Return a filter expression that is `true` when this [`{model}`]\n\
         is contained in `rhs`."
    )
}
