use pulldown_cmark::{CodeBlockKind, Event, Parser, Tag, TagEnd};
use std::env;
use std::fmt::Write;
use std::fs;
use std::path::Path;

/// Templates for each testable Rust code block in README.md, in order.
/// `{snippet}` is replaced with the extracted (and indented) code.
/// If you add or remove a code block in README.md, update this array and
/// adjust the corresponding template.
const README_TEMPLATES: &[&str] = &[
    // Block 0: Model definitions — just needs to compile
    r#"#[allow(unused, dead_code)]
mod readme_models {
    fn main() {
{snippet}
    }
}
"#,
    // Block 1: Usage example — needs model definitions and an async context
    r#"#[allow(unused, dead_code, unused_variables, unused_mut)]
mod readme_usage {
    #[derive(Debug, toasty::Model)]
    struct User {
        #[key]
        #[auto]
        id: u64,
        name: String,
        #[unique]
        email: String,
        #[has_many]
        todos: toasty::schema::HasMany<Todo>,
    }

    #[derive(Debug, toasty::Model)]
    struct Todo {
        #[key]
        #[auto]
        id: u64,
        #[index]
        user_id: u64,
        #[belongs_to(key = user_id, references = id)]
        user: toasty::schema::BelongsTo<User>,
        title: String,
    }

    async fn __compile_check(mut db: toasty::Db) -> toasty::Result<()> {
{snippet}
        Ok(())
    }
}
"#,
];

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let base = Path::new(&manifest_dir).parent().unwrap();

    generate_readme_tests(base, &out_dir);
    generate_guide_tests(base, &out_dir);
}

fn generate_readme_tests(base: &Path, out_dir: &str) {
    let readme_path = base.join("README.md");
    println!("cargo::rerun-if-changed={}", readme_path.display());

    let content = fs::read_to_string(&readme_path).unwrap();
    let blocks = extract_testable_rust_blocks(&content);

    assert_eq!(
        blocks.len(),
        README_TEMPLATES.len(),
        "Expected exactly {} testable rust blocks in README.md, found {}. \
         Update README_TEMPLATES in build.rs if blocks were added or removed.",
        README_TEMPLATES.len(),
        blocks.len()
    );

    let mut output = String::from("// Auto-generated by tests/build.rs — do not edit\n\n");

    for (block, template) in blocks.iter().zip(README_TEMPLATES) {
        output.push_str(&template.replace("{snippet}", &indent(block, 8)));
    }

    // Marker test so the file is not empty
    output.push_str("#[test]\nfn readme_snippets_compile() {}\n");

    let out_path = Path::new(out_dir).join("readme_doc_tests.rs");
    fs::write(&out_path, &output).unwrap();
}

/// Auto-discover guide markdown files and generate doctest modules.
///
/// Each `.md` file in `docs/guide/src/` (except `SUMMARY.md`) becomes a module
/// with the file content attached as a doc comment via `include_str!`. Running
/// `cargo test --doc` then exercises every fenced Rust code block that isn't
/// marked `ignore`, `no_run`, or `compile_fail`.
fn generate_guide_tests(base: &Path, out_dir: &str) {
    let guide_dir = base.join("docs").join("guide").join("src");
    println!("cargo::rerun-if-changed={}", guide_dir.display());

    let mut entries: Vec<_> = fs::read_dir(&guide_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| {
            let path = e.path();
            path.extension().is_some_and(|ext| ext == "md")
                && path.file_name().is_some_and(|name| name != "SUMMARY.md")
        })
        .collect();
    entries.sort_by_key(|e| e.file_name());

    let mut output = String::from("// Auto-generated by tests/build.rs — do not edit\n\n");

    for entry in &entries {
        let path = entry.path();
        let stem = path.file_stem().unwrap().to_str().unwrap();
        let mod_name = stem.replace('-', "_");

        println!("cargo::rerun-if-changed={}", path.display());
        write!(
            output,
            "#[doc = include_str!(r\"{}\")]\nmod {} {{}}\n\n",
            path.display(),
            mod_name
        )
        .unwrap();
    }

    let out_path = Path::new(out_dir).join("guide_doc_tests.rs");
    fs::write(&out_path, &output).unwrap();
}

/// Extract Rust code blocks that should be compile-tested.
///
/// Returns blocks whose info string is plain `rust` (no `no_run`, `ignore`, or
/// `compile_fail` annotation). Blocks with those annotations are skipped.
fn extract_testable_rust_blocks(content: &str) -> Vec<String> {
    let parser = Parser::new(content);

    let skip = ["no_run", "ignore", "compile_fail"];

    let mut blocks = Vec::new();
    let mut current_block: Option<String> = None;

    for event in parser {
        match event {
            Event::Start(Tag::CodeBlock(CodeBlockKind::Fenced(info))) => {
                let annotations: Vec<&str> = info.split(',').map(|s| s.trim()).collect();
                let is_rust = annotations.first().is_some_and(|a| *a == "rust");
                let should_skip = annotations.iter().any(|a| skip.contains(a));

                if is_rust && !should_skip {
                    current_block = Some(String::new());
                }
            }
            Event::Text(text) if current_block.is_some() => {
                current_block.as_mut().unwrap().push_str(&text);
            }
            Event::End(TagEnd::CodeBlock) if current_block.is_some() => {
                let code = current_block.take().unwrap();
                // pulldown-cmark includes a trailing newline; trim it
                blocks.push(code.trim_end().to_string());
            }
            _ => {}
        }
    }

    blocks
}

fn indent(code: &str, spaces: usize) -> String {
    let prefix: String = " ".repeat(spaces);
    code.lines()
        .map(|line| {
            if line.is_empty() {
                String::new()
            } else {
                format!("{prefix}{line}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}
