use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
struct Metadata {
    version: u32,
    labels: Vec<String>,
}

#[derive(Debug, toasty::Model)]
struct ToastyJsonbUser {
    #[key]
    #[auto]
    id: u64,

    #[auto]
    created_at: jiff::Timestamp,

    #[auto]
    updated_at: jiff::Timestamp,

    #[unique]
    #[auto(uuid(v7))]
    sid: uuid::Uuid,

    #[unique]
    #[column(type = varchar(255))]
    email: String,

    //
    #[index]
    #[column(type = varchar(255))]
    name: String,

    age: Option<u8>,

    // #[column(type = jsonb)]
    #[serialize(jsonb, nullable)]
    meta: Option<Metadata>,
}

/*
-- Generated by the database client.
CREATE TABLE toasty_jsonb_users(
    id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    sid uuid NOT NULL,
    email varchar(255) NOT NULL,
    name varchar(255) NOT NULL,
    age smallint,
    meta jsonb,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX index_toasty_jsonb_users_by_sid ON public.toasty_jsonb_users USING btree (sid);
CREATE UNIQUE INDEX index_toasty_jsonb_users_by_email ON public.toasty_jsonb_users USING btree (email);
CREATE INDEX index_toasty_jsonb_users_by_name ON public.toasty_jsonb_users USING btree (name);
*/

#[tokio::main]
async fn main() -> toasty::Result<()> {
    // Build a Db handle, registering all models in this crate
    let mut db = toasty::Db::builder()
        .models(toasty::models!(crate::*))
        // .connect("sqlite::memory:")
        .connect(
            std::env::var("TOASTY_CONNECTION_URL")
                .as_deref()
                // .unwrap_or("sqlite::memory:"),
                .unwrap_or("postgres://127.0.0.1/coder_coder?application_name=toasty-test"),
        )
        .await?;

    // Create tables based on registered models
    // db.push_schema().await?;

    let a = ToastyJsonbUser::filter_by_email("alice@example.com")
        .first()
        .exec(&mut db)
        .await?;

    if a.is_none() {
        // Create a user
        let user = toasty::create!(ToastyJsonbUser {
            name: "Alice",
            email: "alice@example.com",
            age: 12,
            meta: Some(Metadata {
                version: 12,
                labels: vec![],
            })
        })
        .exec(&mut db)
        .await?;

        println!("Created: {:?} - {:?}", user.name, user.meta);
    }

    ToastyJsonbUser::update_by_email("alice@example.com")
        .age(18)
        .meta(Some(Metadata {
            version: 18,
            labels: vec!["good".to_string()],
        }))
        .exec(&mut db)
        .await?;

    // Fetch the user back by primary key
    let found = ToastyJsonbUser::get_by_email(&mut db, "alice@example.com").await?;
    println!("Found: {:?} - {:?}", found.name, found.meta);
    if let Some(v) = found.meta {
        println!("Found: {:?} - {:?}", v.version, v.labels);
        dbg!(v);
    }

    Ok(())
}
