[package]
name = "example-service-ops"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
publish = false

[features]
default = [ "sqlite" ]
mysql = [ "toasty/mysql" ]
postgresql = [ "toasty/postgresql" ]
sqlite = [ "toasty/sqlite" ]

[dependencies]
toasty.workspace = true
tokio.workspace = true
uuid.workspace = true
anyhow = "1"
tracing-subscriber.workspace = true

[[bin]]
name = "server"
path = "src/bin/server.rs"

[lints]
workspace = true
