[book]
title = "Toasty Guide"
authors = ["Toasty Contributors"]

[build]
build-dir = "book"

[preprocessor.toasty-version]
command = "./mdbook-toasty-version"

[output.html]

[output.linkcheck2]
optional = true
