use super::{Ident, ToSql};

use crate::{serializer::Dialect, stmt};

impl ToSql for &stmt::ColumnDef {
    fn to_sql(self, f: &mut super::Formatter<'_>) {
        let name = Ident(&self.name);

        fmt!(f, name " " self.ty);

        if self.not_null {
            fmt!(f, " NOT NULL");
        }

        if self.auto_increment {
            match f.serializer.dialect {
                Dialect::Postgresql => fmt!(f, " GENERATED BY DEFAULT AS IDENTITY"),
                Dialect::Mysql => fmt!(f, " AUTO_INCREMENT"),
                Dialect::Sqlite => {
                    // Sqlite requires that only the primary key is auto
                    // increment. This is validated in ColumnsWithConstraints.
                    fmt!(f, " PRIMARY KEY AUTOINCREMENT")
                }
            }
        }

        if let Some(check) = &self.check {
            fmt!(f, " ");
            check.to_sql(f);
        }

        if f.serializer.is_mysql()
            && let Some(comment) = &self.comment
        {
            fmt!(f, " COMMENT " stmt::Value::String(comment.clone()));
        }
    }
}

impl ToSql for &stmt::CheckConstraint {
    fn to_sql(self, f: &mut super::Formatter<'_>) {
        if let Some(name) = &self.name {
            fmt!(f, "CONSTRAINT " Ident(&name.0) " ");
        }

        fmt!(f, "CHECK (" self.expr ")");
    }
}
