use tests::{models, tests, DbTest};
use toasty::stmt::Id;

async fn auto_uuid_v4(test: &mut DbTest) {
    #[derive(toasty::Model)]
    struct Foo {
        #[key]
        #[auto]
        id: Id<Self>,

        #[auto(uuid(v4))]
        auto_field: uuid::Uuid,
    }

    let db = test.setup_db(models!(Foo)).await;

    let u = Foo::create().exec(&db).await.unwrap();
    // Sanity check that it actually generated a UUID
    assert!(uuid::Uuid::parse_str(&u.auto_field.to_string()).is_ok());
}

async fn auto_uuid_v7(test: &mut DbTest) {
    #[derive(toasty::Model)]
    struct Foo {
        #[key]
        #[auto]
        id: Id<Self>,

        #[auto(uuid(v7))]
        auto_field: uuid::Uuid,
    }

    let db = test.setup_db(models!(Foo)).await;

    let u = Foo::create().exec(&db).await.unwrap();
    // Sanity check that it actually generated a UUID
    assert!(uuid::Uuid::parse_str(&u.auto_field.to_string()).is_ok());
}

async fn auto_increment(test: &mut DbTest) {
    if !test.capability().has_auto_increment {
        return;
    }

    #[derive(toasty::Model)]
    struct Foo {
        #[key]
        #[auto(increment)]
        auto_field: u32,
    }

    let db = test.setup_db(models!(Foo)).await;

    for i in 1..10 {
        let u = Foo::create().exec(&db).await.unwrap();
        assert_eq!(u.auto_field, i);
    }
}

// Foreign key IDs passed to assocations depend on the auto-increment ID generated by the database,
// we want to make sure this works.
async fn auto_increment_with_associations(test: &mut DbTest) {
    if !test.capability().has_auto_increment {
        return;
    }

    #[derive(toasty::Model)]
    struct Foo {
        #[key]
        #[auto(increment)]
        id: u32,

        #[has_many]
        bars: toasty::HasMany<Bar>,
    }

    #[derive(toasty::Model)]
    struct Bar {
        #[key]
        #[auto(increment)]
        id: u32,

        #[index]
        foo_id: u32,

        #[belongs_to(key = foo_id, references = id)]
        #[allow(clippy::disallowed_names)]
        #[allow(dead_code)]
        foo: toasty::BelongsTo<Foo>,
    }

    let db = test.setup_db(models!(Foo, Bar)).await;

    for i in 1..10 {
        let u = Foo::create()
            .bar(Bar::create())
            .bar(Bar::create())
            .exec(&db)
            .await
            .unwrap();
        assert_eq!(u.id, i);
        assert_eq!(u.bars.get()[0].foo_id, i);
        assert_eq!(u.bars.get()[1].foo_id, i);
        assert_eq!(u.bars.get()[0].id, i * 2 - 1);
        assert_eq!(u.bars.get()[1].id, i * 2);
    }
}

tests!(
    auto_uuid_v4,
    auto_uuid_v7,
    auto_increment,
    auto_increment_with_associations
);
