[package]
name = "toasty-driver-d1"
version = "0.9.0"
description = "Cloudflare D1 driver for Toasty"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
categories.workspace = true
readme.workspace = true
documentation = "https://docs.rs/toasty-driver-d1"

[features]
rust_decimal = ["toasty-core/rust_decimal", "toasty-sql/rust_decimal"]
bigdecimal = ["toasty-core/bigdecimal", "toasty-sql/bigdecimal"]
jiff = ["toasty-core/jiff", "toasty-sql/jiff"]

[dependencies]
toasty-core.workspace = true
toasty-sql.workspace = true
tracing.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
async-trait.workspace = true
serde_json.workspace = true
worker = { workspace = true, features = ["d1"] }

[lints]
workspace = true
