[package]
name = "example-hello-toasty-macro"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
toasty = { path = "../../src/toasty" }
toasty-macros = { path = "../../src/macros" }
toasty-sqlite = { path = "../../src/db/sqlite" }

tokio.workspace = true

[features]
default = []
