[package]
name = "example-hello-toasty-macro"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = [ "sqlite" ]
sqlite = [ "toasty/sqlite" ]


[dependencies]
toasty = { path = "../../src/toasty" }
toasty-macros = { path = "../../src/macros" }

tokio.workspace = true
