use crate::prelude::*;

#[driver_test]
pub async fn auto_uuid_v4(test: &mut Test) -> Result<()> {
    #[derive(toasty::Model)]
    struct Item {
        #[key]
        #[auto]
        id: uuid::Uuid,

        #[auto(uuid(v4))]
        auto_field: uuid::Uuid,
    }

    let mut db = test.setup_db(models!(Item)).await;

    let u = Item::create().exec(&mut db).await?;
    // Sanity check that it actually generated a UUID
    assert!(uuid::Uuid::parse_str(&u.auto_field.to_string()).is_ok());
    Ok(())
}

#[driver_test]
pub async fn auto_uuid_v7(test: &mut Test) -> Result<()> {
    #[derive(toasty::Model)]
    struct Item {
        #[key]
        #[auto]
        id: uuid::Uuid,

        #[auto(uuid(v7))]
        auto_field: uuid::Uuid,
    }

    let mut db = test.setup_db(models!(Item)).await;

    let u = Item::create().exec(&mut db).await?;
    // Sanity check that it actually generated a UUID
    assert!(uuid::Uuid::parse_str(&u.auto_field.to_string()).is_ok());
    Ok(())
}

#[driver_test(requires(auto_increment))]
pub async fn auto_increment_explicit(test: &mut Test) -> Result<()> {
    #[derive(toasty::Model)]
    struct Item {
        #[key]
        #[auto(increment)]
        auto_field: u32,
    }

    let mut db = test.setup_db(models!(Item)).await;

    for i in 1..10 {
        let u = Item::create().exec(&mut db).await?;
        assert_eq!(u.auto_field, i);
    }
    Ok(())
}

#[driver_test(requires(auto_increment))]
pub async fn auto_increment_i64_key(test: &mut Test) -> Result<()> {
    #[derive(toasty::Model)]
    struct Item {
        #[key]
        #[auto]
        id: i64,

        name: String,
    }

    let mut db = test.setup_db(models!(Item)).await;

    let first = toasty::create!(Item { name: "first" })
        .exec(&mut db)
        .await?;
    let second = toasty::create!(Item { name: "second" })
        .exec(&mut db)
        .await?;

    assert_eq!(first.id, 1);
    assert_eq!(second.id, 2);

    Ok(())
}

#[driver_test(requires(auto_increment))]
pub async fn auto_increment_implicit(test: &mut Test) -> Result<()> {
    #[derive(toasty::Model)]
    struct Item {
        #[key]
        #[auto]
        auto_field: u32,
    }

    let mut db = test.setup_db(models!(Item)).await;

    for i in 1..10 {
        let u = Item::create().exec(&mut db).await?;
        assert_eq!(u.auto_field, i);
    }
    Ok(())
}

// Test that auto-increment with composite primary keys is rejected
// This only applies to numeric types since UUID uses a different auto strategy
#[driver_test(requires(auto_increment))]
pub async fn auto_increment_with_composite_key_errors(test: &mut Test) {
    #[derive(toasty::Model)]
    #[key(partition = user_id, local = id)]
    struct InvalidModel {
        #[auto(increment)]
        id: u64,

        user_id: u64,
    }

    // This should fail during schema setup
    let result = test.try_setup_db(models!(InvalidModel)).await;

    assert!(result.is_err(), "Expected schema setup to fail");
    let err = result.unwrap_err();
    assert!(
        err.to_string()
            .contains("cannot be used with composite primary keys"),
        "Expected error message about composite keys, got: {}",
        err
    );
}

// Foreign key IDs passed to associations depend on the auto-increment ID
// generated by the database, we want to make sure this works.
#[driver_test(
    requires(auto_increment),
    scenario(crate::scenarios::parent_children_auto_increment)
)]
pub async fn auto_increment_with_association(test: &mut Test) -> Result<()> {
    let mut db = setup(test).await;

    for i in 1..10 {
        let parent = Parent::create()
            .children([Child::create()])
            .exec(&mut db)
            .await?;

        assert_eq!(parent.id, i);
        assert_struct!(parent.children.get()[0], _ { id: == i, parent_id: == i, .. });
    }
    Ok(())
}

// Creating several children at once inserts them with one multi-row statement,
// so the generated IDs have to come back from the database.
#[driver_test(
    requires(and(auto_increment, returning_from_mutation)),
    scenario(crate::scenarios::parent_children_auto_increment)
)]
pub async fn auto_increment_with_associations(test: &mut Test) -> Result<()> {
    let mut db = setup(test).await;

    for i in 1..10 {
        let parent = Parent::create()
            .children([Child::create()])
            .children([Child::create()])
            .exec(&mut db)
            .await?;

        assert_eq!(parent.id, i);
        assert_struct!(parent.children.get()[0], _ { id: == (i * 2 - 1), parent_id: == i, .. });
        assert_struct!(parent.children.get()[1], _ { id: == (i * 2), parent_id: == i, .. });
    }
    Ok(())
}

// A backend without `RETURNING` on mutations cannot report the IDs a multi-row
// insert generated. The statement is rejected instead of answered with IDs
// derived from the first one.
#[driver_test(
    requires(and(auto_increment, not(returning_from_mutation))),
    scenario(crate::scenarios::parent_children_auto_increment)
)]
pub async fn auto_increment_with_associations_is_rejected(test: &mut Test) -> Result<()> {
    let mut db = setup(test).await;

    let err = assert_err!(
        Parent::create()
            .children([Child::create()])
            .children([Child::create()])
            .exec(&mut db)
            .await
    );

    assert!(err.is_unsupported_feature(), "err={err}");
    assert!(
        err.to_string().contains("children"),
        "the error names the value the backend cannot return; err={err}"
    );
    Ok(())
}
