[package]
name = "toasty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toasty-macros = { path = "../macros" }
toasty-core.workspace = true

anyhow = "1"
async-stream = "0.3.5"
async-recursion = "1.0.4"
tokio-stream = { version = "0.1.12", default-features = false }
uuid = { version = "1.3.0", features = ["v4", "fast-rng"] }
indexmap = "2.1.0"
by_address = "1.2.1"
