[package]
name = "toasty"
version = "0.1.0"
edition = "2021"

[features]
default = []
dynamodb = ["dep:toasty-dynamodb"]
postgresql = ["dep:toasty-pgsql"]
sqlite = ["dep:toasty-sqlite"]


[dependencies]
toasty-macros.workspace = true
toasty-core.workspace = true

# Built-in database drivers
toasty-dynamodb = { workspace = true, optional = true }
toasty-pgsql = { workspace = true, optional = true }
toasty-sqlite = { workspace = true, optional = true }

anyhow.workspace = true
async-stream.workspace = true
tokio-stream.workspace = true
uuid.workspace = true
indexmap.workspace = true
by_address.workspace = true
url.workspace = true
