#!/bin/bash

# Exit on error and unset variable usage
set -eu

# Define an array of directory components
directories=(
    "hello-toasty"
    "composite-key"
    "user-has-one-profile"
)

export RUST_BACKTRACE=1

# Function to check if a directory exists
check_directory_exists() {
    if [ ! -d "examples/$1" ]; then
        echo "Directory examples/$1 does not exist." >&2
        exit 1
    fi
}

# Ensure all directories exist
for dir in "${directories[@]}"; do
    check_directory_exists "$dir"
done

# Main loop to execute the command for each directory
for dir in "${directories[@]}"; do
    FEATURES_ARG=""

    if [[ $dir == "hello-toasty" ]]; then
        FEATURES_ARG="--features sqlite"
    fi

    case "$@" in
    run)
        cargo run -p example-$dir $FEATURES_ARG
        ;;
    *)
        cargo check -p example-$dir $FEATURES_ARG
        ;;
    esac
done
