//! Render the synthetic dumper crate (`Cargo.toml` + `src/dumper.rs`) into
//! `<workspace_root>/target/toasty-dump/`.

use super::metadata::{PackageDep, ProjectMetadata};
use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

pub(super) struct Synth {
    pub root: PathBuf,
    pub manifest_path: PathBuf,
}

pub(super) fn write(meta: &ProjectMetadata) -> Result<Synth> {
    let root = meta.workspace_root.join("target").join("toasty-dump");
    let src = root.join("src");
    fs::create_dir_all(&src)
        .with_context(|| format!("creating dumper source dir {}", src.display()))?;

    let manifest_path = root.join("Cargo.toml");
    write_if_changed(&manifest_path, &render_manifest(meta))?;

    let dumper_rs = src.join("dumper.rs");
    write_if_changed(&dumper_rs, DUMPER_SRC)?;

    Ok(Synth {
        root,
        manifest_path,
    })
}

fn write_if_changed(path: &Path, content: &str) -> Result<()> {
    if let Ok(existing) = fs::read_to_string(path)
        && existing == content
    {
        return Ok(());
    }
    fs::write(path, content).with_context(|| format!("writing {}", path.display()))
}

fn render_manifest(meta: &ProjectMetadata) -> String {
    let user_pkg_path = meta.package.manifest_dir.display();

    format!(
        r#"# Auto-generated by toasty-cli. Do not edit.

[package]
name = "toasty-dump"
version = "0.0.0"
edition = "{edition}"
publish = false

[[bin]]
name = "toasty-dumper"
path = "src/dumper.rs"

[dependencies]
{user_pkg_name} = {{ path = "{user_pkg_path}" }}
toasty = {{ {toasty}, features = ["serde"] }}

[workspace]
"#,
        edition = meta.package.edition,
        user_pkg_name = meta.package.name,
        toasty = render_dep_inner(&meta.toasty),
    )
}

fn render_dep_inner(dep: &PackageDep) -> String {
    match &dep.path {
        Some(path) => format!(
            r#"version = "{}", path = "{}""#,
            dep.version,
            path.display()
        ),
        None => format!(r#"version = "{}""#, dep.version),
    }
}

const DUMPER_SRC: &str = r#"// Auto-generated by toasty-cli. Do not edit.

fn main() {
    toasty::__dump_schema();
}
"#;
