//! Render the synthetic dumper crate (`Cargo.toml` + `src/dumper.rs`) into
//! `<target_directory>/toasty-dump/`.

use super::metadata::{PackageDep, ProjectMetadata};
use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

pub(super) struct Synth {
    pub manifest_path: PathBuf,
    /// The cargo target directory to use when building the dumper. Mirrors
    /// the user's resolved target dir so the dep cache is shared.
    pub target_directory: PathBuf,
}

pub(super) fn write(meta: &ProjectMetadata) -> Result<Synth> {
    let root = meta.target_directory.join("toasty-dump");
    let src = root.join("src");
    fs::create_dir_all(&src)
        .with_context(|| format!("creating dumper source dir {}", src.display()))?;

    let manifest_path = root.join("Cargo.toml");
    write_if_changed(&manifest_path, &render_manifest(meta))?;

    let dumper_rs = src.join("dumper.rs");
    write_if_changed(&dumper_rs, &render_dumper_src(meta))?;

    Ok(Synth {
        manifest_path,
        target_directory: meta.target_directory.clone(),
    })
}

fn write_if_changed(path: &Path, content: &str) -> Result<()> {
    if let Ok(existing) = fs::read_to_string(path)
        && existing == content
    {
        return Ok(());
    }
    fs::write(path, content).with_context(|| format!("writing {}", path.display()))
}

fn render_manifest(meta: &ProjectMetadata) -> String {
    let user_pkg_path = meta.package.manifest_dir.to_string_lossy();

    format!(
        r#"# Auto-generated by toasty-cli. Do not edit.

[package]
name = "toasty-dump"
version = "0.0.0"
edition = "{edition}"
publish = false

[[bin]]
name = "toasty-dumper"
path = "src/dumper.rs"

[dependencies]
{user_pkg_name} = {{ path = '{user_pkg_path}' }}
toasty = {{ {toasty} }}

[workspace]
"#,
        edition = meta.package.edition,
        user_pkg_name = meta.package.name,
        toasty = render_toasty_dep(&meta.toasty),
    )
}

fn render_toasty_dep(dep: &PackageDep) -> String {
    let mut parts = vec![format!(r#"version = "{}""#, dep.version)];

    if let Some(path) = &dep.path {
        parts.push(format!("path = '{}'", path.to_string_lossy()));
    }

    if !dep.default_features {
        parts.push("default-features = false".to_string());
    }

    // Mirror the user's feature selection on `toasty`, plus `serde` (the
    // dumper needs `app::Schema` to be `Serialize`). Dedup so we don't
    // emit `serde` twice when the user already enabled it.
    let mut features: Vec<String> = dep.features.clone();
    if !features.iter().any(|f| f == "serde") {
        features.push("serde".to_string());
    }
    let feat_list = features
        .iter()
        .map(|f| format!(r#""{f}""#))
        .collect::<Vec<_>>()
        .join(", ");
    parts.push(format!("features = [{feat_list}]"));

    parts.join(", ")
}

fn render_dumper_src(meta: &ProjectMetadata) -> String {
    // `extern crate` forces the linker to pull in the user's rlib, so its
    // `inventory::submit!` registrations are present in the binary. Without
    // this, nothing in the synthesized `main` references the user crate and
    // the linker drops it — leaving zero models in the inventory.
    let crate_ident = meta.package.name.replace('-', "_");

    format!(
        r#"// Auto-generated by toasty-cli. Do not edit.

extern crate {crate_ident};

fn main() {{
    toasty::__dump_schema();
}}
"#
    )
}
