pub mod belongs_to_configured;
pub mod belongs_to_one_way;
pub mod belongs_to_self_referential;
pub mod bigdecimal;
pub mod decimal;
pub mod field_auto;
pub mod field_column_name;
pub mod field_column_type;
pub mod one_model_crud;
